### ISSUE TITLE
加载阿里云模型的时候展示不出来了

### ISSUE THREAD

**Issue by yiwuxing** [sanyuered/WeChat-MiniProgram-AR-3D#1]
我把gltf模型传到阿里云oss上，然后把链接换成阿里云的oss链接但是展示不出来，想问下是什么原因

**Comment by sanyuered** [comment]
1、在微信公众平台，登录进入您的小程序开发者管理界面，将gltf模型的地址添加到request合法域名。
2、你可以打开小程序自带的调试模式，看是否能展示。
3、小程序调试模式自带vconsole工具，模型加载的日志会显示在vconsole里。
